// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj0CJUhh62s3zdYinL_4n-iRsM4Qp0_Dw',
    appId: '1:548839313356:web:2d5af52e96a20c510ed769',
    messagingSenderId: '548839313356',
    projectId: 'dental-auth',
    authDomain: 'dental-auth.firebaseapp.com',
    storageBucket: 'dental-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNfnvph_uWOxhPm_2ZFqQxpMhJlJM9umM',
    appId: '1:548839313356:android:3ae2a17c28dcd12e0ed769',
    messagingSenderId: '548839313356',
    projectId: 'dental-auth',
    storageBucket: 'dental-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANsPZXWyyGGPL8l5pCICSTSc4gF0CVxCE',
    appId: '1:548839313356:ios:0f6a79f467704db60ed769',
    messagingSenderId: '548839313356',
    projectId: 'dental-auth',
    storageBucket: 'dental-auth.appspot.com',
    iosClientId: '548839313356-ge9hjlpb1m9ouur3l6cf6d5gl1v27m39.apps.googleusercontent.com',
    iosBundleId: 'com.example.dentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANsPZXWyyGGPL8l5pCICSTSc4gF0CVxCE',
    appId: '1:548839313356:ios:40286a642fe611f30ed769',
    messagingSenderId: '548839313356',
    projectId: 'dental-auth',
    storageBucket: 'dental-auth.appspot.com',
    iosClientId: '548839313356-2d5lik5fsjevrbbuhcp6kdoc9ofb099m.apps.googleusercontent.com',
    iosBundleId: 'com.example.dentalApp.RunnerTests',
  );
}
